apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k8s
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: zoho-api.helo-k8s.fun
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: zoho-api
            port:
              number: 3002
  tls:
  - hosts:
    - zoho-api.helo-k8s.fun
    secretName: zoho-api.helo-k8s.fun-tls