apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pv
  namespace: jellyfin
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 20Gi
