apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pv        # < name of the persistent volume claim ("pvc'")
  namespace: jellyfin       # < namespace where place the pvc

spec:
  storageClassName: linode-block-storage-retain
  volumeName: jellyfin-pv # < the pv it will "claim" to storage. Created in the previous yaml.
  accessModes:
    - ReadWriteMany         # < Multiple pods can write to storage. Same value as pv
  resources:
    requests:
      storage: 20Gi          # < How much data can the pvc claim from pv